// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SagaDemo.LoyaltyPointsAPI.DataAccess;

namespace SagaDemo.LoyaltyPointsAPI.DataAccess.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20190427094023_UserIdAndTransactionIdIndex")]
    partial class UserIdAndTransactionIdIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SagaDemo.LoyaltyPointsAPI.DataAccess.Entities.PointsChangedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PointChange");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("UserId");

                    b.Property<DateTime>("UtcDateTimeRecorded");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("PointsChangedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
