//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.2.4.0 (NJsonSchema v9.13.36.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using SagaDemo.Common.Errors.Swagger;

namespace SagaDemo.DeliveryAPI.ApiClient
{
    #pragma warning disable

    

    

    #pragma warning restore
}